import { System } from "@/types/interface";

export const systemsDesc: System[] = [
  {
    id: "SYS001",
    type: '32"',
    name: "Premium Gaming",
    playerPhone: undefined,
    description:
      "High-end setup with 4K monitor, gaming headphones, premium chair",
    playerName: "Jane Smith",
    startTime: new Date(Date.now() - 30 * 60 * 1000),
    controllerCount: 4,
    status: "paused",
    totalAmount: 220.0,
    duration: 30 * 60,
    pausedDuration: 5 * 60,
    ratePerSecond: 0.8,
    hourlyRate: 288,
    maxControllers: 6,
  },
  {
    id: "SYS002",
    type: '55"',
    name: "Ultimate Gaming",
    playerPhone: "+91 8095240976",
    description: "Large screen with surround sound, racing wheel, VR ready",
    playerName: "Bob Wilson",
    startTime: new Date(Date.now() - 90 * 60 * 1000),
    controllerCount: 3,
    status: "completed",
    totalAmount: 450.0,
    duration: 90 * 60,
    pausedDuration: 0,
    ratePerSecond: 1.2,
    hourlyRate: 432,
    maxControllers: 8,
  },
  {
    id: "SYS003",
    type: '27"',
    name: "Standard Gaming",
    playerPhone: "+91 8095240976",
    description: 'Basic gaming setup with 27" monitor, comfortable chair',
    playerName: "John Doe",
    startTime: new Date(Date.now() - 45 * 60 * 1000),
    controllerCount: 2,
    status: "active",
    totalAmount: 135.5,
    duration: 45 * 60,
    pausedDuration: 0,
    ratePerSecond: 0.5,
    hourlyRate: 180,
    maxControllers: 4,
  },

  {
    id: "SYS004",
    type: '24"',
    name: "Standard Gaming 2",
    playerPhone: "+91 8095240976",
    description: "Backup system, same specs as Standard Gaming",
    playerName: "",
    startTime: new Date(),
    controllerCount: 1,
    status: "available",
    totalAmount: 0,
    duration: 0,
    pausedDuration: 0,
    ratePerSecond: 0.5,
    hourlyRate: 180,
    maxControllers: 4,
  },
];
